import React,{useEffect,useState} from 'react';
import {createRoot} from 'react-dom/client';
import {Activity,AlertTriangle,Database,Gauge,Orbit,Radar,RefreshCw,Search,Shield,Satellite,X,Zap} from 'lucide-react';
import './styles.css';
const API=import.meta.env.VITE_API_URL||'http://localhost:8000';
const fmtPc=n=>n==null?'—':Number(n).toExponential(2);
const risk=pc=>pc>=1e-4?'CRITICAL':pc>=1e-5?'HIGH':pc>=1e-6?'MEDIUM':'LOW';
function App(){
 const [stats,setStats]=useState(null),[sats,setSats]=useState([]),[events,setEvents]=useState([]),[query,setQuery]=useState(''),[selected,setSelected]=useState(null),[loading,setLoading]=useState(true),[refreshing,setRefreshing]=useState(false);
 const load=()=>{setRefreshing(true);Promise.all([fetch(`${API}/api/stats`).then(r=>r.json()),fetch(`${API}/api/satellites`).then(r=>r.json()),fetch(`${API}/api/events`).then(r=>r.json())]).then(([a,b,c])=>{setStats(a);setSats(b);setEvents(c)}).catch(()=>{}).finally(()=>{setLoading(false);setRefreshing(false)})};
 useEffect(load,[]);
 const filtered=sats.filter(s=>`${s.name} ${s.norad_id}`.toLowerCase().includes(query.toLowerCase())).slice(0,7),top=events[0];
 return <div className="shell"><aside><div className="brand"><Orbit/><div><b>SATCOLLIVO</b><small>ORBITAL SAFETY</small></div></div><nav><a className="active"><Gauge/>Overview</a><a><Satellite/>Objects</a><a><Radar/>Conjunctions</a><a><AlertTriangle/>Threats</a><a><Zap/>Maneuvers</a><a><Database/>Data</a></nav><div className="prototype"><Shield/><div><b>DECISION SUPPORT</b><span>Prototype calculations. Validate before operational use.</span></div></div></aside>
 <main><header><div><p>MISSION CONTROL / OVERVIEW</p><h1>Orbital Situation</h1></div><div className="online"><i/> SYSTEM ONLINE</div></header>
 <section className="metrics"><Card label="TRACKED RECORDS" value={stats?.total_records??'—'} icon={<Satellite/>}/><Card label="RECORDED EVENTS" value={events.length} icon={<Radar/>}/><Card label="TOP COLLISION Pc" value={top?fmtPc(top.probability_of_collision):'—'} icon={<Activity/>}/><Card label="MANEUVERS FLAGGED" value={events.filter(e=>e.maneuver_recommended).length} icon={<Zap/>}/></section>
 <section className="grid"><div className="panel orbit-panel"><div className="panel-head"><div><span>LIVE ORBITAL VIEW</span><small>Current catalog visualization</small></div><button onClick={load}><RefreshCw size={14} className={refreshing?'spin':''}/> SYNC</button></div><div className="space"><div className="orbit o1"/><div className="orbit o2"/><div className="orbit o3"/><div className="earth"><div className="continent c1"/><div className="continent c2"/></div><div className="sat s1">●<label>PRIMARY</label></div><div className="sat s2">●</div><div className="sat s3">●</div></div><div className="telemetry"><span>SGP4 PROPAGATION</span><span>DPWC UNCERTAINTY</span><span>25 KM SCREEN</span></div></div>
 <div className="panel search-panel"><div className="panel-head"><div><span>OBJECT EXPLORER</span><small>Search catalog by name or NORAD</small></div></div><div className="search"><Search size={16}/><input placeholder="ISS, 25544..." value={query} onChange={e=>setQuery(e.target.value)}/></div><div className="sat-list">{filtered.map(s=><button key={s.norad_id} onClick={()=>setSelected(s)} className={selected?.norad_id===s.norad_id?'chosen':''}><span><b>{s.name||'UNKNOWN OBJECT'}</b><small>NORAD {s.norad_id}</small></span><em>{s.object_type||'UNKNOWN'}</em></button>)}{!filtered.length&&!loading&&<div className="empty">No objects match the search.</div>}</div></div></section>
 <section className="panel events"><div className="panel-head"><div><span>RECENT CONJUNCTION EVENTS</span><small>Stored assessment history</small></div></div><div className="table"><div className="tr th"><span>PRIMARY</span><span>SECONDARY</span><span>TCA</span><span>MISS DIST.</span><span>Pc</span><span>RISK</span></div>{events.slice(0,6).map((e,i)=><div className="tr event-row" key={i}><span>#{e.primary_norad_id}</span><span>#{e.secondary_norad_id}</span><span>{new Date(e.tca).toLocaleString()}</span><span>{Number(e.miss_distance_km).toFixed(3)} km</span><span className="mono">{fmtPc(e.probability_of_collision)}</span><span><strong className={`risk ${risk(e.probability_of_collision).toLowerCase()}`}>{risk(e.probability_of_collision)}</strong></span></div>)}{!events.length&&!loading&&<div className="empty">No assessments recorded yet. Ingest orbital data and run an assessment to populate this console.</div>}</div></section>
 </main>{selected&&<div className="drawer"><div className="drawer-head"><div><span>OBJECT PROFILE</span><h2>{selected.name||'UNKNOWN OBJECT'}</h2></div><button onClick={()=>setSelected(null)}><X/></button></div><div className="profile-id">NORAD {selected.norad_id}</div><div className="detail-grid"><Detail label="OBJECT TYPE" value={selected.object_type}/><Detail label="SOURCE" value={selected.source}/><Detail label="SENSOR" value={selected.sensor}/><Detail label="RCS SIZE" value={selected.rcs_size||'UNKNOWN'}/><Detail label="TLE EPOCH" value={selected.epoch}/><Detail label="FETCHED" value={selected.fetched_at}/></div><div className="notice"><Shield size={17}/><span>Position and velocity are propagated from the latest stored TLE using SGP4.</span></div></div>}</div>}
function Card({label,value,icon}){return <div className="metric"><div>{icon}</div><span>{label}</span><b>{value}</b><small>LIVE DATABASE</small></div>};function Detail({label,value}){return <div className="detail"><span>{label}</span><b>{value||'—'}</b></div>};createRoot(document.getElementById('root')).render(<App/>);
