import React, {useEffect, useMemo, useState} from 'react';
import {createRoot} from 'react-dom/client';
import {Activity, AlertTriangle, Database, Gauge, Orbit, Radar, RefreshCw, Search, Shield, Satellite, Settings2, Zap, X, Play, ChevronRight, Clock3, Target, CircleDot, CheckCircle2, Loader2} from 'lucide-react';
import './styles.css';

const API=import.meta.env.VITE_API_URL||'http://localhost:8000';
const fmtPc=(n)=>n==null?'—':Number(n).toExponential(2);
const risk=(pc)=>pc>=1e-4?'CRITICAL':pc>=1e-5?'HIGH':pc>=1e-6?'MEDIUM':'LOW';
const fmtTime=(v)=>v?new Date(v).toLocaleString([], {year:'numeric',month:'short',day:'2-digit',hour:'2-digit',minute:'2-digit'}):'—';

async function get(path){const r=await fetch(`${API}${path}`);if(!r.ok)throw new Error((await r.json().catch(()=>({}))).detail||`Request failed (${r.status})`);return r.json()}
async function post(path,body){const r=await fetch(`${API}${path}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});if(!r.ok)throw new Error((await r.json().catch(()=>({}))).detail||`Request failed (${r.status})`);return r.json()}

function App(){
 const [view,setView]=useState('overview'),[stats,setStats]=useState(null),[sats,setSats]=useState([]),[events,setEvents]=useState([]),[query,setQuery]=useState(''),[selected,setSelected]=useState(null),[orbit,setOrbit]=useState(null),[assessment,setAssessment]=useState(null),[loading,setLoading]=useState(true),[error,setError]=useState('');
 const load=async()=>{setLoading(true);try{const [s,a,e]=await Promise.all([get('/api/stats'),get('/api/health'),get('/api/events?limit=50')]);setStats(s);setEvents(e);setError(a.status==='online'?'':'API offline')}catch(e){setError(e.message)}finally{setLoading(false)}};
 useEffect(()=>{load();get('/api/satellites?search=25544&limit=1').then(x=>x[0]&&selectSatellite(x[0])).catch(()=>{})},[]);
 useEffect(()=>{const t=setTimeout(()=>{get(`/api/satellites?search=${encodeURIComponent(query)}&limit=100`).then(setSats).catch(e=>setError(e.message))},180);return()=>clearTimeout(t)},[query]);
 async function selectSatellite(s){setSelected(s);setError('');try{const o=await get(`/api/satellites/${s.norad_id}/orbit?duration_minutes=120&step_seconds=60`);setOrbit(o)}catch(e){setError(e.message)}}
 async function runAssessment(opts){setAssessment({status:'queued',request:opts});try{const j=await post('/api/assessments',opts);setAssessment(x=>({...x,jobId:j.job_id,status:'running'}));const timer=setInterval(async()=>{try{const r=await get(`/api/assessments/${j.job_id}`);setAssessment(x=>({...x,...r}));if(r.status==='complete'||r.status==='failed'){clearInterval(timer);if(r.status==='complete')await load()}}catch(e){clearInterval(timer);setAssessment(x=>({...x,status:'failed',error:e.message}))}},1000)}catch(e){setAssessment({status:'failed',error:e.message})}}
 const nav=[['overview','Overview',Gauge],['objects','Objects',Satellite],['conjunctions','Conjunctions',Radar],['threats','Threats',AlertTriangle],['maneuvers','Maneuvers',Zap],['data','Data',Database]];
 const threatEvents=events.filter(e=>e.probability_of_collision>=1e-6);
 return <div className="shell"><aside><div className="brand"><Orbit/><div><b>SATCOLLIVO</b><small>ORBITAL SAFETY</small></div></div><nav>{nav.map(([id,label,Icon])=><button key={id} onClick={()=>setView(id)} className={view===id?'active':''}><Icon/>{label}</button>)}</nav><div className="prototype"><Shield/><div><b>DECISION SUPPORT</b><span>Prototype calculations. Validate before operational use.</span></div></div></aside><main><header><div><p>MISSION CONTROL / {view.toUpperCase()}</p><h1>{view==='overview'?'Orbital Situation':view==='objects'?'Tracked Objects':view==='conjunctions'?'Conjunction Assessment':view==='threats'?'Threat Monitor':view==='maneuvers'?'Maneuver Analysis':'Data & System Health'}</h1></div><div className="header-actions"><div className="online"><i/> SYSTEM ONLINE</div><button className="icon-btn" onClick={load} title="Refresh"><RefreshCw size={15}/></button></div></header>
 {error&&<div className="errorbar"><AlertTriangle size={14}/>{error}<button onClick={()=>setError('')}><X size={13}/></button></div>}
 {view==='overview'&&<Overview stats={stats} events={events} sats={sats} selected={selected} orbit={orbit} onSelect={selectSatellite} onAssess={runAssessment} setView={setView} loading={loading} query={query} setQuery={setQuery}/>} 
 {view==='objects'&&<Objects sats={sats} query={query} setQuery={setQuery} selected={selected} onSelect={selectSatellite}/>} 
 {view==='conjunctions'&&<Events events={events} onAssess={runAssessment} selected={selected} onSelectEvent={(e)=>setSelected({norad_id:e.primary_norad_id,name:e.primary?.name})}/>} 
 {view==='threats'&&<Threats events={threatEvents} onSelect={(e)=>setView('conjunctions')}/>} 
 {view==='maneuvers'&&<Maneuvers events={events.filter(e=>e.maneuver_recommended)}/>} 
 {view==='data'&&<DataView stats={stats}/>} 
 {assessment&&<AssessmentModal data={assessment} onClose={()=>setAssessment(null)}/>} 
 </main></div>
}

function Overview({stats,events,sats,selected,orbit,onSelect,onAssess,setView,loading,query,setQuery}){const top=events[0];return <>
 <section className="metrics"><Card label="TRACKED RECORDS" value={stats?.total_records??'—'} icon={<Satellite/>}/><Card label="UNIQUE OBJECTS" value={stats?.unique_objects??'—'} icon={<Target/>}/><Card label="TOP COLLISION Pc" value={top?fmtPc(top.probability_of_collision):'—'} icon={<Activity/>}/><Card label="MANEUVERS FLAGGED" value={stats?.maneuver_count??0} icon={<Zap/>}/></section>
 <section className="actionbar"><div><b>Assessment target</b><span>{selected?`${selected.name} · NORAD ${selected.norad_id}`:'Select a primary satellite'}</span></div><div className="action-controls"><select defaultValue="24" id="hours"><option value="1">1 hour</option><option value="6">6 hours</option><option value="24">24 hours</option><option value="48">48 hours</option></select><button className="primary" disabled={!selected} onClick={()=>onAssess({primary_norad_id:selected.norad_id,hours:Number(document.getElementById('hours').value),screening_km:25,top:10})}><Play size={14}/> RUN ASSESSMENT</button></div></section>
 <section className="grid"><div className="panel orbit-panel"><PanelHead title="SGP4 ORBITAL TRACK" sub={orbit?`${orbit.name} · 120 min propagation`:'Select an object to propagate'} action={<span className="live-tag">LIVE PROPAGATION</span>}/><OrbitView orbit={orbit}/><div className="telemetry"><span>FRAME: TEME</span><span>STEP: 60 SEC</span><span>{orbit?`${orbit.points.length} SAMPLES`:'NO TRACK'}</span></div></div><div className="panel search-panel"><PanelHead title="OBJECT EXPLORER" sub="Search catalog by name or NORAD"/><div className="search"><Search size={16}/><input placeholder="ISS, 25544..." value={query} onChange={e=>setQuery(e.target.value)}/></div><div className="sat-list">{sats.slice(0,8).map(s=><ObjectRow key={s.norad_id} s={s} chosen={selected?.norad_id===s.norad_id} onClick={()=>onSelect(s)}/>)}</div><button className="see-all" onClick={()=>setView('objects')}>VIEW FULL CATALOG <ChevronRight size={13}/></button></div></section>
 <section className="panel events"><PanelHead title="RECENT CONJUNCTION EVENTS" sub="Stored assessment history" action={<button className="text-btn" onClick={()=>setView('conjunctions')}>VIEW ALL <ChevronRight size={13}/></button>}/><EventTable events={events.slice(0,6)} loading={loading}/></section>
 </>}
function Objects({sats,query,setQuery,selected,onSelect}){return <section className="panel full"><PanelHead title="TRACKED OBJECT CATALOG" sub={`${sats.length} objects currently loaded`} /><div className="catalog-toolbar"><div className="search"><Search size={16}/><input placeholder="Search name or NORAD ID" value={query} onChange={e=>setQuery(e.target.value)}/></div><span className="hint">CelesTrak / latest epoch per NORAD</span></div><div className="catalog-grid">{sats.map(s=><ObjectCard key={s.norad_id} s={s} selected={selected?.norad_id===s.norad_id} onClick={()=>onSelect(s)}/>)}</div></section>}
function Events({events,onAssess,selected,onSelectEvent}){return <><section className="actionbar"><div><b>Conjunction assessment</b><span>{selected?`${selected.name} · NORAD ${selected.norad_id}`:'Select a satellite from Objects first'}</span></div><button className="primary" disabled={!selected} onClick={()=>onAssess({primary_norad_id:selected.norad_id,hours:24,screening_km:25,top:20)}><Play size={14}/> RUN 24H ASSESSMENT</button></section><section className="panel full"><PanelHead title="CONJUNCTION REGISTER" sub="Highest-risk recorded events"/><EventTable events={events} onSelect={onSelectEvent}/></section></>}
function Threats({events}){return <section className="panel full"><PanelHead title="THREAT MONITOR" sub="Events above Pc 1×10⁻⁶"/><div className="threat-grid">{events.length?events.map(e=><div className="threat-card" key={e.id}><div className="threat-top"><strong className={`risk ${risk(e.probability_of_collision).toLowerCase()}`}>{risk(e.probability_of_collision)}</strong><span>{fmtTime(e.tca)}</span></div><h3>{e.primary?.name||`NORAD ${e.primary_norad_id}`}</h3><p>vs {e.secondary?.name||`NORAD ${e.secondary_norad_id}`}</p><div className="threat-stats"><span><b>{e.miss_distance_km?.toFixed?.(3)||e.miss_distance_km}</b> km miss</span><span><b>{fmtPc(e.probability_of_collision)}</b> Pc</span></div></div>):<Empty text="No elevated threats in the stored assessment history."/>}</div></section>}
function Maneuvers({events}){return <section className="panel full"><PanelHead title="MANEUVER ANALYSIS" sub="Prototype decision-support recommendations"/><div className="maneuver-list">{events.length?events.map(e=>{const m=e.maneuver_details||{};return <div className="maneuver-card" key={e.id}><div><strong>{e.primary?.name||`NORAD ${e.primary_norad_id}`}</strong><span>vs {e.secondary?.name||`NORAD ${e.secondary_norad_id}`}</span></div><div><small>ΔV</small><b>{m.delta_v_m_s!=null?`${m.delta_v_m_s} m/s`:'—'}</b></div><div><small>DIRECTION</small><b>{m.direction_ric||'—'}</b></div><div><small>BURN TIME</small><b>{m.burn_time?fmtTime(m.burn_time):'—'}</b></div><div><small>TARGET Pc</small><b>{m.target_pc?fmtPc(m.target_pc):'—'}</b></div></div>}):<Empty text="No maneuver recommendations have been stored."/>}</div><div className="notice"><Settings2 size={15}/><span>Maneuver values are prototype linearized estimates and are not flight-ready commands. Validate with full numerical re-propagation before operational use.</span></div></section>}
function DataView({stats}){return <div className="data-grid"><section className="panel"><PanelHead title="DATABASE" sub="SQLite tracking store"/><div className="data-list"><DataRow label="Tracked records" value={stats?.total_records}/><DataRow label="Unique NORAD objects" value={stats?.unique_objects}/><DataRow label="CelesTrak records" value={stats?.by_source?.CELESTRAK||0}/><DataRow label="Payloads" value={stats?.by_object_type?.PAYLOAD||0}/><DataRow label="Debris" value={stats?.by_object_type?.DEBRIS||0}/><DataRow label="Latest fetch" value={fmtTime(stats?.latest_fetch)}/></div></section><section className="panel"><PanelHead title="SYSTEM PIPELINE" sub="Current integration status"/><div className="pipeline"><Pipe ok label="SQLite database"/><Pipe ok label="CelesTrak ingestion"/><Pipe ok label="SGP4 propagation"/><Pipe ok label="Conjunction engine"/><Pipe ok label="Probability of collision"/><Pipe ok label="Maneuver planner"/><Pipe ok label="React mission console"/></div></section></div>}
function AssessmentModal({data,onClose}){return <div className="overlay"><div className="modal"><div className="modal-head"><div><span>ASSESSMENT JOB</span><h2>{data.status==='complete'?'Assessment complete':data.status==='failed'?'Assessment failed':'Running conjunction assessment'}</h2></div><button className="icon-btn" onClick={onClose}><X size={17}/></button></div>{data.status!=='complete'&&data.status!=='failed'?<div className="progress"><Loader2 className="spin" size={28}/><b>Propagating tracked objects…</b><span>Altitude pre-filter → TCA search → covariance → Pc</span></div>:data.status==='failed'?<div className="failure"><AlertTriangle/><b>{data.error}</b></div>:<><div className="assessment-summary"><span><small>PRIMARY</small><b>{data.result.primary.name}</b></span><span><small>CANDIDATES</small><b>{data.result.candidate_count}</b></span><span><small>PREFILTERED</small><b>{data.result.skipped_by_altitude}</b></span><span><small>WINDOW</small><b>{data.result.window_hours}h</b></span></div><EventTable events={data.result.events}/></>}<button className="secondary wide" onClick={onClose}>{data.status==='complete'?'CLOSE':'RUNNING…'}</button></div></div>}
function EventTable({events=[],loading,onSelect}){return <div className="table"><div className="tr th"><span>PRIMARY</span><span>SECONDARY</span><span>TCA</span><span>MISS DIST.</span><span>Pc</span><span>RISK</span></div>{events.map((e,i)=><div className="tr clickable" key={e.id||i} onClick={()=>onSelect?.(e)}><span>{e.primary?.name||`#${e.primary_norad_id}`}</span><span>{e.secondary?.name||`#${e.secondary_norad_id}`}</span><span>{fmtTime(e.tca)}</span><span>{Number(e.miss_distance_km).toFixed(3)} km</span><span className="mono">{fmtPc(e.probability_of_collision)}</span><span><strong className={`risk ${risk(e.probability_of_collision).toLowerCase()}`}>{risk(e.probability_of_collision)}</strong></span></div>)}{!events.length&&!loading&&<Empty text="No conjunction events recorded yet. Select a primary satellite and run an assessment."/>}</div>}
function ObjectRow({s,chosen,onClick}){return <button onClick={onClick} className={chosen?'chosen':''}><span><b>{s.name||'UNKNOWN OBJECT'}</b><small>NORAD {s.norad_id}</small></span><em>{s.object_type||'UNKNOWN'}</em></button>}
function ObjectCard({s,selected,onClick}){return <button className={`object-card ${selected?'selected':''}`} onClick={onClick}><div className="object-icon"><Satellite size={18}/></div><div><b>{s.name||'UNKNOWN OBJECT'}</b><small>NORAD {s.norad_id}</small></div><span>{s.object_type||'UNKNOWN'}</span></button>}
function OrbitView({orbit}){if(!orbit)return <div className="orbit-empty"><Orbit size={32}/><b>SELECT A SATELLITE</b><span>SGP4 propagation will render its actual trajectory here.</span></div>;const pts=orbit.points;const xs=pts.map(p=>p.x),ys=pts.map(p=>p.y),zs=pts.map(p=>p.z);const minX=Math.min(...xs),maxX=Math.max(...xs),minY=Math.min(...ys),maxY=Math.max(...ys);const minZ=Math.min(...zs),maxZ=Math.max(...zs);const map=(p)=>{const x=25+(p.x-minX)/Math.max(1,maxX-minX)*50;const y=25+(p.y-minY)/Math.max(1,maxY-minY)*50;return [x,y]};const d=pts.map((p,i)=>{const [x,y]=map(p);return `${i?'L':'M'} ${20+x*3.2} ${20+y*3.2}`}).join(' ');const last=pts[pts.length-1];const [lx,ly]=map(last);return <svg className="orbit-svg" viewBox="0 0 240 240"><defs><radialGradient id="earth"><stop offset="0" stopColor="#2c7895"/><stop offset=".7" stopColor="#0c3044"/><stop offset="1" stopColor="#06121b"/></radialGradient></defs><circle cx="120" cy="120" r="39" fill="url(#earth)" stroke="#3e90aa"/><circle cx="120" cy="120" r="46" fill="none" stroke="#16475d" strokeDasharray="2 4"/><path d={d} fill="none" stroke="#65e3ff" strokeWidth="1.4" opacity=".9"/><circle cx={20+lx*3.2} cy={20+ly*3.2} r="3.5" fill="#fff" className="current-dot"/><text x="14" y="226" fill="#557180" fontSize="6">ACTUAL SGP4 PROPAGATION · {orbit.points.length} POINTS</text><text x="14" y="14" fill="#557180" fontSize="6">ECI PROJECTION · TEME</text></svg>}
function PanelHead({title,sub,action}){return <div className="panel-head"><div><span>{title}</span><small>{sub}</small></div>{action}</div>}
function Card({label,value,icon}){return <div className="metric"><div>{icon}</div><span>{label}</span><b>{value}</b><small>LIVE DATABASE</small></div>}
function DataRow({label,value}){return <div className="data-row"><span>{label}</span><b>{value??'—'}</b></div>}
function Pipe({ok,label}){return <div className="pipe"><CheckCircle2 size={16}/><span>{label}</span><b>{ok?'READY':'OFFLINE'}</b></div>}
function Empty({text}){return <div className="empty">{text}</div>}

createRoot(document.getElementById('root')).render(<App/>);
